language: php

addons:
    #chrome: stable
    apt:
        packages:
        - apache2
        - postfix
        - libapache2-mod-fastcgi
        - libappindicator1
        - fonts-liberation

cache:
  directories:
    - $HOME/.composer/cache

sudo: required
dist: trusty

php:
  - 7.2

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled


before_install:
  # Apache & php-fpm configuration
  - bash travis-scripts/setup-php-fpm.sh
  - bash travis-scripts/setup-apache.sh

  # PrestaShop configuration
  - cp tests/parameters.yml.travis app/config/parameters.yml

script:
  - composer install --prefer-dist --no-interaction --no-progress
  - bash travis-scripts/install-prestashop
  - bash ./travis-scripts/run-selenium-tests

after_script:
  - php -i
  - sudo cat /var/log/apache2/error.log
  - curl -L http://localhost/
  - cat /etc/apache2/envvars
  - cat /etc/apache2/sites-available/000-default.conf
  - sudo cat /var/log/php-fpm.log
  - sudo ls -l /var/log/apache2
  - sudo cat /var/log/apache2/other_vhosts_access.log
  - cat $TRAVIS_BUILD_DIR/var/log/dev.log
