language: php

addons:
    #chrome: stable
    apt:
        packages:
        - apache2
        - postfix
        - libapache2-mod-fastcgi
        - libappindicator1
        - fonts-liberation
        - mysql-utilities

cache:
  directories:
    - $HOME/.composer/cache

sudo: required
dist: trusty

#php:
#  - 5.4
#  - 5.6
#  - 7.0

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
        - PRESTASHOP_REFERENCE_VERSION=1.7.0.1

matrix:
  include:
#    - php: 7.1
      # temporarily disabled
#      env: EXTRA_TESTS=functional
    - php: 7.1
      env: EXTRA_TESTS=sqldiff

before_install:
  # Apache & php-fpm configuration
  - bash travis-scripts/setup-php-fpm.sh
  - bash travis-scripts/setup-apache.sh

  # PrestaShop configuration
  - cp tests/parameters.yml.travis app/config/parameters.yml


notifications:
  hipchat: ec4e21c5eb82066ba8be5fd1afefde@1184657

script:
  - composer install --prefer-dist --no-interaction --no-progress
  - bash travis-scripts/install-prestashop
  - bash ./travis-scripts/diff-upgrade-db

after_script:
  - sudo cat /var/log/apache2/error.log
  - docker logs upgrade-test # Created in sqldiff step

after_failure:
  - curl -L http://localhost/
  - cat /etc/apache2/envvars
  - cat /etc/apache2/sites-available/000-default.conf
  - sudo cat /var/log/php-fpm.log
  - sudo ls -l /var/log/apache2
  - sudo cat /var/log/apache2/other_vhosts_access.log
