language: php

sudo: false

services:
  - docker
  
cache:
  directories:
    - $HOME/.composer/cache

addons:
    sauce_connect: true

sudo: required
dist: trusty
group: edge

php:
  - 5.6
  - 7.0
    
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_install:
  - mysql -e 'create database prestashop;'
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "memory_limit = 512M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f tests/travis-ci-apache-vhost /etc/apache2/sites-available/default
  - sudo cp -Rf . /var/www/prestashop.unit.test
  - sudo chmod 777 -R /var/www/
  - sudo service apache2 restart

before_script:
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - cp tests/parameters.yml.travis app/config/parameters.yml
  - composer install --no-interaction --no-progress
  - docker-compose up -d
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo $(phpenv version-name)
  #- echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  #- echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

script:
  - tests/check_php_parse_errors.sh
  - docker exec -t prestashop_mysql_1 mysqldump -uroot -pdoge prestashop > /tmp/db.sql
  - docker exec -t prestashop_prestashop_1 php bin/phpunit -c tests/
  - docker exec -t prestashop_prestashop_1 php bin/phpunit -c admin-dev/
  - docker-compose rm -fv
  - docker-compose up -d
  - bash ./travis-scripts/run-selenium-tests

after_script:
  - firefox --version
